nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Quests App
            description: This is an app, that provides users to complete the quests!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc|doc.json)$) # Accepts routes under /api except /api/doc
